handleGHRelease: true
manifest: true
releaseType: java-yoshi
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
    branch: 9.0.x-lts
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
    branch: 8.0.x-lts
  