handleGHRelease: true
manifest: true
bumpMinorPreMajor: true
packageName: gcp-lts-bom
branches:
    - branch: 9.0.x-lts
    - branch: 8.0.x-lts
    - branch: 7.0.x-lts
    - branch: 6.0.x-lts
    - branch: protobuf-4.x-rc
      releaseType: java-yoshi
