handleGHRelease: true
manifest: true
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    packageName: gcp-lts-bom
    branch: 9.0.x-lts
  - bumpMinorPreMajor: true
    handleGHRelease: true
    packageName: gcp-lts-bom
    branch: 8.0.x-lts
  - bumpMinorPreMajor: true
    handleGHRelease: true
    packageName: gcp-lts-bom
    branch: 7.0.x-lts
  - bumpMinorPreMajor: true
    handleGHRelease: true
    packageName: gcp-lts-bom
    branch: 6.0.x-lts
