handleGHRelease: true
manifest: true
releaseType: java-yoshi
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 9.0.x-lts
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 8.0.x-lts
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 7.0.x-lts
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 6.0.x-lts


