name: 'Linkage Monitor'
description: 'Checks the compatibility of the library with the latest Libraries BOM'
runs:
  using: "composite"
  steps:
    - name: Download Linkage Monitor uber JAR
      # scripts/release.sh updates the version part in the URL
      run: |
        curl --output /tmp/linkage-monitor.jar \
        "https://storage.googleapis.com/cloud-opensource-java-linkage-monitor/linkage-monitor-1.4.93-SNAPSHOT-all-deps.jar"
      shell: bash
    - run: java -jar /tmp/linkage-monitor.jar com.google.cloud:libraries-bom
      shell: bash
